//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS317Program {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS317Program.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array Is Sorted.
        /// </summary>
        internal static string ArrayIsSortedName {
            get {
                return ResourceManager.GetString("ArrayIsSortedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ArrayIsSortedValue {
            get {
                return ResourceManager.GetString("ArrayIsSortedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brute Force Password Generator C#.
        /// </summary>
        internal static string BruteForcePasswordGeneratorCSharpName {
            get {
                return ResourceManager.GetString("BruteForcePasswordGeneratorCSharpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string BruteForcePasswordGeneratorCSharpValue {
            get {
                return ResourceManager.GetString("BruteForcePasswordGeneratorCSharpValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brute Force Password Generator.
        /// </summary>
        internal static string BruteForcePasswordGeneratorName {
            get {
                return ResourceManager.GetString("BruteForcePasswordGeneratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string BruteForcePasswordGeneratorValue {
            get {
                return ResourceManager.GetString("BruteForcePasswordGeneratorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble Sort.
        /// </summary>
        internal static string BubbleSortName {
            get {
                return ResourceManager.GetString("BubbleSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string BubbleSortValue {
            get {
                return ResourceManager.GetString("BubbleSortValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorial Calculator.
        /// </summary>
        internal static string FactorialCalculatorName {
            get {
                return ResourceManager.GetString("FactorialCalculatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string FactorialCalculatorValue {
            get {
                return ResourceManager.GetString("FactorialCalculatorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Sort.
        /// </summary>
        internal static string MergeSortName {
            get {
                return ResourceManager.GetString("MergeSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string MergeSortValue {
            get {
                return ResourceManager.GetString("MergeSortValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Sort.
        /// </summary>
        internal static string QuickSortName {
            get {
                return ResourceManager.GetString("QuickSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string QuickSortValue {
            get {
                return ResourceManager.GetString("QuickSortValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QuitName {
            get {
                return ResourceManager.GetString("QuitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string QuitValue {
            get {
                return ResourceManager.GetString("QuitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Directory Search.
        /// </summary>
        internal static string TelephoneDirectorySearchName {
            get {
                return ResourceManager.GetString("TelephoneDirectorySearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TelephoneDirectorySearchValue {
            get {
                return ResourceManager.GetString("TelephoneDirectorySearchValue", resourceCulture);
            }
        }
    }
}
